const events = {
  MENU_VIEWED: 'MENU_VIEWED',
  RECIPE_TAPPED: 'RECIPE_TAPPED',
  LOG_VIEWED: 'LOG_VIEWED',
  RATING_VIEWED: 'RATING_VIEWED',
  LOGS_VIEWED: 'LOGS_VIEWED',
  SETTINGS_VIEWED: 'SETTINGS_VIEWED',
};

export default events;
